[target.thumbv6m-none-eabi]
runner = "probe-rs run --no-location --chip RP2040"
#runner = "elf2uf2-rs -d"
#runner = "picotool load -u -v -x -t elf"

[target.thumbv7m-none-eabi]
runner = "probe-rs run --no-location --chip STM32F103C8"

[target.thumbv8m.main-none-eabihf]
runner = "probe-rs run --no-location --chip RP235x"
#runner = "elf2uf2-rs -d"
#runner = "picotool load -u -v -x -t elf"

[target.xtensa-esp32-none-elf]
runner = "espflash flash -S --monitor --chip esp32"
#runner = "probe-rs run --no-location --chip esp32"
rustflags = [
  "-C", "target-cpu=esp32",
]

[build]
target = "thumbv6m-none-eabi"          # RP2040
#target = "thumbv7m-none-eabihf"       # STM32
#target = "thumbv8m.main-none-eabihf"  # RP235x

[env]
DEFMT_LOG = "info"